"""add pet_id to sightings

Revision ID: 2006559a2d83
Revises: ae440fbabbfa
Create Date: 2026-09-21 03:05:52.213046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2006559a2d83'
down_revision: Union[str, Sequence[str], None] = 'ae440fbabbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sightings', sa.Column('pet_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sightings_pet_id'), 'sightings', ['pet_id'], unique=False)
    op.create_foreign_key(None, 'sightings', 'pets', ['pet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sightings', type_='foreignkey')
    op.drop_index(op.f('ix_sightings_pet_id'), table_name='sightings')
    op.drop_column('sightings', 'pet_id')
    # ### end Alembic commands ###
